default: &default
  adapter: mysql2
  encoding: utf8
  pool: 30
  username: root
  password: root

development:
  <<: *default
  database: hospital

test:
  <<: *default
  database: hospital_test

production:
  <<: *default
  # database: <%= ENV['PRAYER_DATABASE_DATABASE'] %>
  # username: <%= ENV['PRAYER_DATABASE_USERNAME'] %>
  # password: <%= ENV['PRAYER_DATABASE_PASSWORD'] %>