default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: root
  host: localhost

development:
  <<: *default
  database: hospital

test:
  <<: *default
  database: hospital_test

production:
  <<: *default
  database: hospital
  # database: <%= ENV['PRAYER_DATABASE_DATABASE'] %>
  # username: <%= ENV['PRAYER_DATABASE_USERNAME'] %>
  # password: <%= ENV['PRAYER_DATABASE_PASSWORD'] %>